### ISSUE TITLE
Energy Dashboard - Energy Import

### ISSUE THREAD

**Issue by JensenNick** [JensenNick/huawei_solar_pees#22]
Using `sensor.energy_import` as input sensor in the Energy Dashboard has caused failure of the sensor 'Energy Import Cost' which HA has created - when HA is rebooted. The input sensor is created as a platform sensor.

```
  - platform: integration
    source: sensor.power_import
    name: "Energy Import"
    unique_id: energy_import
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
```

![2024-01-30_08-37-17](https://github.com/JensenNick/huawei_solar_pees/assets/149193835/97e1d003-271e-4910-a6c1-631a2f95e104)

**Comment by JensenNick** [comment]
I've asked about the behavior of the sensor created by HA in the HA forum.
https://community.home-assistant.io/t/platform-integration-sensor-crashing-in-energy-dashboard/681769

**Comment by JensenNick** [comment]
I have added Energy Utility Meters to all of the platform energy sensors. This seams to be the solution recommended by the HA community.

History log add7272704b160a4600d6a295004167158231a88

https://community.home-assistant.io/t/how-i-solved-a-reset-of-an-integral/540322/2

**Comment by Roving-Ronin** [comment]
@JensenNick of your using the utility_meter and also wanting (it appears) to have the cost of all those sensors (import / export / battery and even different tariff periods), you'd be better looking at the energy_utility integration.

Works like the utility_meter but with a few more functions to allow defining from_grid or to_grid and calling a sensor with the energy cost (import or export) 

Easy as to implement just like a utility_meter but automatically creates all the cost / compensation sensors.

Add in tariffs and you end up with tracking for every single tariff type and cost (& and then add hourly/daily/weekly/monthly/quarterly/yearly versions). 
In the Energy Dashboard (or other cards) then allows easily seeing peak/shoulder/offpeak energy and costs and same for battery.

Also works for gas and water btw, not just electricity.

**Comment by Roving-Ronin** [comment]
If of interest see: https://github.com/zeronounours/HA-custom-component-energy-meter

**Comment by JensenNick** [comment]
> of your using the utility_meter and also wanting (it appears) to have the cost of all those sensors
No, the input for the Energy Dashboard is a platform: integral sensor. Nothing fancy at all and the input is from the Huawei Solar integration. I've tried to fix this without any success.
```yaml
  - platform: integration
    source: sensor.power_import
    name: "Energy Import"
    unique_id: energy_import
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
```

**Comment by JensenNick** [comment]
I will leave this "issue" as "open" but "locked", so it appears in the

**Comment by JensenNick** [comment]
I haven't encountered this issue for the last 6 months. I'll close the issue permanently.
