### ISSUE TITLE
Feature request: Enhanced Energy Management Dashboards 

### ISSUE THREAD

**Issue by heinemannj** [JensenNick/huawei_solar_pees#58]
You are looking at this time to raw Huawei Solar and PEES values which is helpful for debugging purpose.
Monitoring of all EMS dependant components in one view is basic and mandatory in future:

![image](https://github.com/JensenNick/huawei_solar_pees/assets/3251642/2b785c76-3eb5-4224-b882-b0e88a1e8b49)

![image](https://github.com/JensenNick/huawei_solar_pees/assets/3251642/bb1b9ea5-b97c-46b0-a13a-0b662aaf21d3)

Merging is possible but only after heavy adaptation of sensor naming conventions ...
I strongly disagree on your actual sensor namings.

**My approach**: **To be much close to the nameing conventions provided by @wlcrs huawei_solar** and all other integrations I needs to synchronize:

- huawei_solar
- epexspot
- tibber
- sun
- sun2
- solcast
- emhass
- myVaillant
- dwd_DeutscherWetterdienst
- Shelly
- ...

It works as **visible in above screenshoots**!

For sure tons of bugs and a lot of improvement - but I need clear readable and short sensor names for proper debugging on all integration dependencies ...

**Comment by heinemannj** [comment]
I've made a quick and dirty review of your code.

My view:

- Very complex
- Hardly to maintain
- Not closely enough to @wlcrs naming convention

My conclusion:

- I will step out

**Sorry for the noise ...**

**Comment by JensenNick** [comment]
No worries. I’m afraid we all have our own ide about naming. I’ve had no intention but to keep a unique naming to avoid any conflicts.
