### ISSUE TITLE
Feature request: Enhanced Top Level Power/Energy Flow Dashboard

### ISSUE THREAD

**Issue by heinemannj** [JensenNick/huawei_solar_pees#59]
Monitoring of all EMS Power/Energy Flows in one view is basic and mandatory in future:

![image](https://github.com/JensenNick/huawei_solar_pees/assets/3251642/12f5e726-e98f-4332-bb65-232a51e832ce)

Merging is possible but only after heavy adaptation of sensor naming conventions ...
I strongly disagree on your actual sensor namings.

**My approach**: **To be much close to the nameing conventions provided by @wlcrs huawei_solar** and all other integrations I needs to synchronize:

- huawei_solar
- epexspot
- tibber
- sun
- sun2
- solcast
- emhass
- myVaillant
- dwd_DeutscherWetterdienst
- Shelly
- ...

It works as **visible in above screenshoots**!

For sure tons of bugs and a lot of improvement - but I need clear readable and short sensor names for proper debugging on all integration dependencies ...

**Comment by heinemannj** [comment]
I've made a quick and dirty review of your code.

My view:

- Very complex
- Hardly to maintain
- Not closely enough to @wlcrs naming convention

My conclusion:

- I will step out

**Sorry for the noise ...**

**Comment by JensenNick** [comment]
Presentation in Lovelace is very individual, but it would be great to biuld a base for people to start with. It has not been my main priority. It’s on the roadmap.
