### ISSUE TITLE
Feature request: Forecast and Prediction EMS Dashboards

### ISSUE THREAD

**Issue by heinemannj** [JensenNick/huawei_solar_pees#60]
You are looking at this time to raw Huawei Solar and PEES values which is helpful for debugging purpose.
In addition you are on the way to integrate historical data - Very good.

But only looking into the past and to the future at the same time will safe our Earth and our money ...

![image](https://github.com/JensenNick/huawei_solar_pees/assets/3251642/aaee93c0-7221-4fcc-ae45-d7baf9b13b53)

From my perspective the most complex task:

- Weather forcast
- Solar forecast
- Energy price forcast
- Artifizielle Intelligenz (AI) or
- Machine learning (ML)
- ...

A lot of different integrations to be synchronized ...

=> `Battery Charge-Discharge automation` is key!

![image](https://github.com/JensenNick/huawei_solar_pees/assets/3251642/289c6332-f317-4c4c-b075-261b7bf381a5)

**My approach**: **To be much close to the nameing conventions provided by @wlcrs huawei_solar** and all other integrations I needs to synchronize:

- huawei_solar
- epexspot
- tibber
- sun
- sun2
- solcast
- emhass
- myVaillant
- dwd_DeutscherWetterdienst
- Shelly
- ...

It works as **visible in above screenshoots**!

For sure tons of bugs and a lot of improvement - but I need clear readable and short sensor names for proper debugging on all integration dependencies ...

**Comment by heinemannj** [comment]
I've made a quick and dirty review of your code.

My view:

- Very complex
- Hardly to maintain
- Not closely enough to @wlcrs naming convention

My conclusion:

- I will step out

**Sorry for the noise ...**

**Comment by JensenNick** [comment]
Agree, battery charge and discharge automations based on solar forcast and energy prices are key. Don’t forget your carharger. It is way beyond the scope of this project and my skills to create a universal automation which everyone can adapt. I’m working on my own setups in NodeRed, but they are based on my specific situation and setup.
